pysal/segregation

README.md

Adding auxiliary installation instructions for the development version in `README.md`:
```
pip install git+https://github.com/pysal/segregation
```

add second install option to README.md

---

.travis.yml

Using [`/miniconda/Miniconda-latest-Linux-x86_64.sh`](https://github.com/pysal/segregation/blob/0613b5ceeee95cd0334bf59ff5af37d48f86095e/.travis.yml#L22) in [.travis.yml](https://github.com/pysal/segregation/blob/master/.travis.yml) pulls an archaic version of `Miniconda`. 
```
- wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
```
Instead, we should specifically be pulling the latest version of `Miniconda3` from Travis testing.

directly specifiy Miniconda3

---

MANIFEST.in
setup.py

This is targeted at fixing the [conda errors](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/24466537#L731).
This is missing in the [submodule directions for pysal](https://github.com/pysal/submodule_template/pull/13).

BUG: adding MANIFEST.in so requirements.txt gets included in sdist

---

segregation/non_spatial_indexes.py
segregation/spatial_indexes.py

This is a PR that address https://github.com/pysal/segregation/issues/18.
I've been working in this issue and pushed this commit here with several approaches for all centralization indexes with this new argument:
```
center        : string, tuple or integer.
This defines what is considered to be the center of the spatial context under study.
If string, this can be set to:
"mean": the center longitude/latitude is the mean of longitudes/latitudes of all units. 
"median": the center longitude/latitude is the median of longitudes/latitudes of all units. 
"population_weighted_mean": the center longitude/latitude is the mean of longitudes/latitudes of all units weighted by the total population.
"largest_population": the center longitude/latitude is the centroid of the unit with largest total …
```

OK: Create additional argument for the center in Centralization indexes

---

README.md
notebooks/spatial_examples.ipynb
segregation/spatial_indexes.py
segregation/tests/test_absolute_clustering.py

This PR adds the Absolute Clustering segregation measure (originally, only the Relative Clustering was present)
This adds/updates:
- function itself
- test
- notebook
- readme
It uses the exponential decay distance and also matches the values of OasisR using `spatmat = "d"` in the `ACL` function.

add Absolute Clustering (ACL) segregation measure

---

segregation/inference_wrappers.py

This adds the bootstrap approach for single value. The size of the samples generated in each permutation is the same as the original sample size. Note that this resamples the units.... this could also be extended to generate samples from the individual. But I think that this current approach is already valuable to add in the module.
One thing that I noticed is that this approach is very sensitive to the sample size (which in our case is always fixed and the number of rows in the dataset... we could flexibilize that also), which might be a desired property. It is very likely that this approach generates distributions around the original sample estimate which, consequently, flagging not significant segregation measures. At least for eveness dimensions (dissimilarty, gini, etc.) I honestly …

add bootstrap (for unit levels) for single value segregation

---

segregation/spatial_indexes.py
segregation/tests/test_absolute_concentration.py
segregation/tests/test_perimeter_area_ratio_spatial_dissimilarity.py
segregation/tests/test_relative_concentration.py

I've been studying deeply OasisR and one thing that I originally spotted that might be wrong was also discussed in Tivadar (2019). 
I'm comparing all of our function with the R implementation and, so far, I'm getting the exact same results. However, for the Perimeter_Area_Ratio_Spatial_Dissim this PR changes the formula to
rather than the original version of Wong (1993):
In terms of changing values, this is not very substantial for the examples I'm running locally.
The Notes in the doctrings mentioned this.

change denominator of spatial interaction term of Perimeter_Area_Ratio_Spatial_Dissim (and also add some tweak for concentration indexes)

---

.travis.yml

The current configuration of dual travis testing is not right. By putting [conda install --yes --file requirements.txt;](https://github.com/pysal/segregation/blob/master/.travis.yml#L42) after the pypi/github installation of `libpysal`, all travis tests actually install conda-forge release of `libpysal` although we want to test against the github version.
This PR tries to resolve the issue.

(bug) dual testing aganist pypi and github versions of libpysal

---

README.md
notebooks/multigroup_aspatial_examples.ipynb
segregation/aspatial/multigroup_aspatial_indexes.py
segregation/tests/test_multi_divergence.py

This implements the index presented in Roberto, Elizabeth. "The Divergence Index: A Decomposable Measure of Segregation and Inequality." arXiv preprint arXiv:1508.01167 (2015). The results are similar to the Multigroup Information Theory index.
This is the index used in Roberto, Elizabeth. "The Spatial Proximity and Connectivity Method for Measuring and Analyzing Residential Segregation." Sociological Methodology 48.1 (2018): 182-224.
ps.: the spatial version of it is accomplished by replacing the p_i by "tilde p_i"  just as in the network use case.
The formula of the index add in this PR follows:

adds Multigroup Divergence Index of Roberto (2018)

---

doc/conf.py

This tries to fix https://github.com/pysal/segregation/issues/58
After a long time debugging, this was succesfully built in ReadTheDocs website.

create mocks for c dependency libraries

---

README.md
segregation/spatial/spatial_indexes.py

This address the issue raised in https://github.com/pysal/segregation/issues/96.

Generalize also for haversine distance

---

segregation/tests/test_decomposition.py

This adds the plotting methods of the decomposition for the tests.
This will considerably increase the coverage %.
I tested locally, and this works just fine.

enh: add plotting tests in the decomposition framework

---

requirements_tests.txt

Travis Build was breaking. I think this will solve the issue since all the tests are pointing to this .txt.

bug: add descartes in requirements_tests for plotting tests

---

segregation/spatial/spatial_indexes.py

This PR is closely related to https://github.com/pysal/segregation/issues/96. This adds a more robust condition that raises for the user what is actually happening during the calculations.
@ljwolf shared with me an example using cenpy for a GeoDataFrame with a large unit for the centroid and realized that the RelativeClustering measure was behaving unexpectedly. It worked for Phoenix, but not for Tucson (was returning an NaN). However, in that case, even for Phoenix the index might be problematic since numerically the internal calculations are unstable. For Phoenix we got virtually zero for the exp(-d) of the distances:
And for Tucson we were having equal zero (therefore resulting in a NaN index):
The commit of this PR fix this and raises an informative ValueError better and perform a …

add robust and informative condition for large magnitude projections (tests only off-diagonal)

---

segregation/aspatial/multigroup_aspatial_indexes.py
segregation/inference/inference_wrappers.py
segregation/tests/test_inference.py

This PR adds the "evenness" and "bootstrap" approach for MultiGroup indexes as raised in https://github.com/pysal/segregation/issues/86. Some of the formattings were changed as I thought It was easier to spot which lines to change in the code and how to properly construct the null hypothesis.
I assumed that the evenness approach is simply the generalization of the single group approach, as every unit had a fixed vector of probability of allocating for each subgroup. However, the difference is that now the simulation is a multinomial distribution in the tract level. So, we need to simulate many multinomial distributions and I achieved that using a `map` function.
This is still a WIP since I'd like to add the `random_label` approach for comparing two Multigroup Measures.
Edit: I added the …

Adds inference wrappers for multigroup indexes (Single and Two)

---

README.md

This PR updates the link to the documentation following #149, etc. and also adds a docs badge. It may also be worth adding the `http://pysal.org/segregation/` link to the **About** section (repository details).

updates docs link

---

.github/workflows/build_docs.yml
.github/workflows/unittests.yml
.github/workflows/upload_package.yml
setup.py

This PR updates:
* `setup.py`:
* correct website
* supported Python versions
* `build_docs.yml`
* streamlined syntax
* add caching
* `unittests.yml`
* add nightly cron job
* streamlined syntax
* `upload_package.yml`
* bump `actions/checkout` and `actions/setup-python` versions

GHA and setup.py maintenance

---

segregation/_base.py
segregation/decomposition/decompose_segregation.py
segregation/multigroup/multi_dissim.py
segregation/multigroup/multi_divergence.py
segregation/multigroup/multi_diversity.py
segregation/multigroup/multi_gini.py
segregation/multigroup/multi_info_theory.py
segregation/multigroup/multi_norm_exposure.py
segregation/multigroup/multi_relative_diversity.py
segregation/multigroup/multi_squared_coef_var.py
segregation/multigroup/simpsons_concentration.py
segregation/multigroup/simpsons_interaction.py
segregation/singlegroup/boundary_spatial_dissim.py
segregation/singlegroup/par_dissim.py

- fix warning for islands (currently it will raise an error if triggered, we're calling `warnings` instead of `warnings.warn`)
- allow extra kwargs in multigroup indices
- faster densifying W in pardissim and bsd

fix warning in length-weighted W matrix

---

segregation/singlegroup/gini.py

Motivation for this and a performance evaluation are [here](https://gist.github.com/sjsrey/788b937413be263d6f7ec094f7ea205a). This replaces #170

feat: memory efficient and performant gini

---

.ci/310.yml
.ci/38.yml
.ci/39.yml
environment.yml
requirements.txt

Not sure why pygeos is in requirements and CI ends here as it doesn't seem to be used in the code. Removing.

remove pygeos

---

.github/workflows/unittests.yml

Update unittests.yml --  add manual trigger -- CI has been disabled for 3 months

Update unittests.yml -- add manual trigger

---

segregation/inference/inference_wrappers.py
segregation/inference/randomization.py
segregation/singlegroup/gini.py

- plot with ax instead of plt in twovalue test
- allow 'verbose' argument in simulator (to avoid the same warning repeating on each iteration)
- avoid OMP warning from numba

use ax instead of plt
