- segregation/counterfactual.py
this PR starts a function to generate counterfactual variables for two cities using the "unit share" approach. Still need to add the other two approaches
> start counterfactual

- segregation/counterfactual.py
- segregation/plot.py
- rework some of the parameter names in `generate_counterfactual`
- new decomposition function that takes segregation classes (should be pretty easy to refactor once we move to #4)
- convenience function for plotting lorenz curves
> add working decomposition func and lorenz plotting func

- segregation/counterfactual.py
- segregation/plot.py
plot the real lorenz curve this time
> add lorenz

- .travis.yml
- doc/_static/pysal-styles.css
- readthedocs.yml
This follows the guidelines discussed in our last meeting following https://github.com/pysal/giddy/pull/92 and https://github.com/pysal/spaghetti/pull/261.
Best,
Renan
> Tweaks for july release

- doc/generated/segregation.inference.SingleValueTest.rst
- doc/generated/segregation.inference.TwoValueTest.rst
- doc/generated/segregation.network.get_osm_network.rst
- notebooks/inference_wrappers_example.ipynb
This is two small tweaks:
- update `Compare_Segregation` to `TwoValueTest` in a markdown cell in the inference notebook.
- rename the generated file names inference files for sphinx
> Renan final tweak release

- README.md
tiny fix to get coveralls badge to update more frequently
> add github tag to coveralls badge

- README.md
> remove erroneous reference to geodetaframe in multigroup section

- README.md
this fixes the issue with the coveralls badge not updating
> coveralls badge fix

- doc/index.rst
small tweak since the former link was broken
> fix the broken link to compute all in readthe docs

- segregation/network/network.py
- segregation/spatial/spatial_indexes.py
this adds the spatial version of the multigroup divergence index
> add spatial divergence index

- environment.yml
- requirements.txt
- segregation/inference/inference_wrappers.py
- use tqdm instead of print statements for measuring progress
- return axes for diagnostic plots
> inference wrapper tweaks

- segregation/spatial/spatial_indexes.py
As mentioned in https://github.com/pysal/segregation/pull/116#discussion_r303654880
> remove W from importings in spatial_indexes

- segregation/tests/test_bias_corrected_dissimilarity.py
- segregation/tests/test_compute_all.py
- segregation/tests/test_inference.py
- segregation/tests/test_modified_dissimilarity.py
- segregation/tests/test_modified_gini.py
It addresses #123.
It covers inference, some segregation indexes and inference wrappers.
> Change precision of simulated-based tests.

- requirements.txt
This addresses https://github.com/pysal/segregation/issues/127.
> update scikit-learn requirements

- notebooks/decomposition_wrapper_example.ipynb
- notebooks/inference_wrappers_example.ipynb
- segregation/aspatial/aspatial_indexes.py
- segregation/aspatial/multigroup_aspatial_indexes.py
- segregation/spatial/spatial_indexes.py
- segregation/util/util.py
This implements https://github.com/pysal/segregation/pull/130#issuecomment-522137184. So, this is PR is open in favor of https://github.com/pysal/segregation/pull/130.
> Raise an informative error when input data have NAs (also update geosnap links)

- segregation/inference/inference_wrappers.py
This improves the inference discussion in the docstrings.
> improve inference wrappers docstring

- README.md
> resolving broken link

- .travis.yml
> addressing pysal/pysal#1145

- requirements.txt
- segregation/__init__.py
- tools/gitcount.ipynb
- bump version 
- update requirements.txt
- update gitcount notebook
> prepare v2.1.0

- notebooks/kl_divergence_profile_walkthrough.ipynb
- segregation/spatial/kl_divergence_profile.py
Hi there,
This comprises the primary outputs of my Google Summer of Code (GSoC) project - working to implement a tool to calculate the KL Divergence Profile segregation metric from Olteanu et al.'s 2019 paper, ['Segregation through the multiscalar lens'](https://doi.org/10.1073/pnas.1900192116)
For further information on the project, please see the project's [GitHub repository](https://github.com/noahbouchier/GSoC-PySAL-21), including a [summary document](https://github.com/noahbouchier/GSoC-PySAL-21/blob/master/NoahBouchier_GSoC21_NumFOCUS_PySAL_Summary.md) of the project's achievements.
Having worked hard to create this function, it is now in the home straight of review, refinement and feedback before being implemented into PySAL's library.
I look forward to responding to the feedback …
> Commit of `kl_divergence_profile` function and walkthrough notebook - following Google Summer of Code 2021

- segregation/inference/comparative.py
- add pin for minimum pyproj
- test on 3.10
- pop spatial args from inference
> pyproj pin

- segregation/_base.py
- segregation/singlegroup/modified_dissim.py
> fix sim logic in modified dissim

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/noop.txt
- requirements_tests.txt
> init dev container recipe

- .github/workflows/upload_package.yml
> GHA: update release action for pyproject

- .github/workflows/unittests.yml
* This PR adds explicit testing against Intel & Apple Silicon on macOS
* xref https://github.com/pysal/pysal/issues/1298
> macOS testing -- Intel & Apple Silicon CI -- update testing.yml

- segregation/singlegroup/absolute_centralization.py
> (bug) numpy 2.0 is not supporting np.NaN

- segregation/inference/comparative.py
resolves #234 (and some ruff formatting)
> fix crs concat
